# Generated by Django 3.1 on 2020-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothings',
            new_name='Clothing',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
