# Generated by Django 3.1 on 2020-08-27 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0003_auto_20200824_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 9, 59, 31, 805668, tzinfo=utc)),
        ),
    ]
