# Generated by Django 3.1 on 2020-08-27 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0004_clothing_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='clothing',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 18, 31, 52, 119439, tzinfo=utc)),
        ),
    ]
