# Generated by Django 3.1 on 2020-08-28 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0005_auto_20200827_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 21, 33, 58, 992494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='phone',
            field=models.CharField(max_length=128),
        ),
    ]
